### ISSUE TITLE
EthStats improvements

### ISSUE THREAD

**Issue by baxy** [nanspro/parity-demo-alethio#2]
Hi @nanspro, thanks for your great work, I have some improvements/fixes regarding EthStats that I would like to add:

1. Namings, I would like EthStats to be evidentiate more. "network-server" => EthStats Server, "network stats dashboard" => EthStats Dashboard, etc...
2. If you installed the lite mode version of the server through the docker compose examples in the `ethstats-network-server` repo, you will see there that the dashboard is already included, so no need to install it again, only if installed separalty...
3. Also a description of each component of EthStats (ethstats-network-server, ethstats-cli, ethstats-network-dashboard), and that they also all available on docker hub as images (https://hub.docker.com/u/alethio), simpler installation...
4. Mention that server pushes data to the dashboard realtime through Deepstream (https://github.com/deepstreamIO/deepstream.io), 3rd party service installed automatically if in the setup process are used the docker compose example files, mandatory for the tool to work
5. If the server lite mode is needed with persistence, then another mandatory dependency is required, Redis (https://redis.io)

Thanks,
Adrian

**Comment by nanspro** [comment]
@baxy made these changes!!!

**Comment by baxy** [comment]
Hi @nanspro, 

You added a note: 

> Note: If you are running server in lite-mode with memory persistence then dashboard will be downloaded/running automatically in parallel so no need for further installation.

From this I understand that the dashboard is running automatically if I run the server in lite mode and with memory persistence. This is not quite true. If you git clone the server and start it, the tool is incomplete and won't work. That's why we created in the server's repo 2 docker compose example files to help understand how the installation of the entire tool with all dependencies  (dashboard, deepstream, redis) needs to be done. The dashboard is already included in those docker compose files as an image pulled from docker hub. Same for Deepstream and Redis (if persistence is used), without them the server will not work. This is very important to know. 

The tutorial should explain only a method of setting up the tool with all necessary steps. I recommend the one through docker compose because it's simpler and easier. 
1. Install the server
    - Explain dependencies in the docker compose file
        - server
        - dashopard
        - deepstream
        - redis (if persistence is used)
2. Install ethstats-cli
    - Explain how to connect to server and Parity (this part is OK)
3. Access dashboard
    - Depending what you have in the docker compose file set up for the dashboard (default: http://localhost) you'll be able to see your nodes in the private network.

**Comment by nanspro** [comment]
@baxy  ahh sorry for that, i understood it now and have updated accordingly!!
I am still showing the dashboard installation instructions (with an note that it is not required), do you want me to remove that?

**Comment by baxy** [comment]
Yes please, and also update the order of the steps like in my last comment, first the server needs to be installed. 

Thank you

**Comment by nanspro** [comment]
@baxy done!!!
